#!/bin/bash
#must have bwfmetaedit and textmate installed to work
config_file="$HOME/.$(basename "${0}").conf"
touch $config_file
source $config_file

usage(){
echo "-h (help) -e (edit config), (-p) generate pbcore instantiation doc, (-o) enable overwrite"
exit 0  
}
file_input="$1"
OPTIND=1
while getopts "hp:o:e" opt ; do 
    case "${opt}" in
        h) usage ;;
        p) runtype="pb" && file_input="$2";;
        o) runtype="overwrite" && file_input="$2";;
        e) runtype="edit";;
        *) echo "bad option -$OPTARG" ; usage ;;
        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
    esac
done

if [ "${*}" = "" ] ; then
    usage
fi

#Error Function
_error_exit(){
    echo -e "\033[1;32m"$1"\033[0m" 1>&2
    exit 1
}

# Set up variables
orig_short="${file_input##*/}"
orig_ref="${orig_short%.*}"


# Check length of Originator Reference against 32 character limit (pulled from file name)
if
	(("${#orig_short}" > 32));
then
	orig_ref="See description for Identifiers"
fi

# Option to generate PB Core Instantiation Doc
if [ "$runtype" = "pb" ] ; then
    mediainfo --output=PBCore2 "$file_input" >"${file_input%.*}"_pbcoreinstantiationdocument.xml
	exit 0
fi

# Option to Edit Configuration File

if [ "$runtype" = "edit" ] ; then
	echo "#INSERT YOUR VALUES BETWEEN THE QUOTES AND SAVE FILE" > "${config_file}"
	echo "originator=\"$originator\"" >> "${config_file}"
	echo "history=\"$history\"" >> "${config_file}"
	echo "IARL=\"$IARL\"" >> "${config_file}"
	mate $config_file
	exit 0
fi


# Run bwfmetaedit with selected settings on input file
date=$(getfileinfo "$file_input" | grep "created" | cut -d ' ' -f2)
date_normalized=$(date -jf "%m/%d/%Y" "${date}" +%Y-%m-%d)
time=$(getfileinfo "$file_input" | grep "created" | cut -d ' ' -f3)

if [ "$runtype" = "overwrite" ] ; then
    bwfmetaedit --Description="${file_input##*/}" --Originator="$originator" --OriginatorReference="$orig_ref" --History="$history" --IARL="$IARL" --MD5-Embed --OriginationDate="$date_normalized" \
    --OriginationTime="$time" "$file_input"
else 
    bwfmetaedit --reject-overwrite --Description="${file_input##*/}" --Originator="$originator" --OriginatorReference="$orig_ref" --History="$history" --IARL="$IARL" --MD5-Embed --OriginationDate="$date_normalized" \
    --OriginationTime="$time" "$file_input"
fi


#Report Coding History for confirmation
echo -e "\033[1;95m ************ \033[0m"
echo -e "\033[1;93m Process complete. \033[0m"
echo -e "\033[1;93m The coding history contains the following values. \033[0m"
echo -e "\033[1;93m Please check for accuracy. \033[0m"
mediainfo -f "$file_input" | grep "Encoding settings" | cut -c 44-
echo -e "\033[1;95m ************ \033[0m"

