#!/bin/bash
#must have bwfmetaedit and textmate installed to work
config_file="$HOME/.$(basename "${0}").conf"
touch $config_file
source $config_file
orig_short="${1##*/}"
orig_ref=${orig_short%.*}


# Check length of Originator Reference against 32 character limit (pulled from file name)
if
	((${#orig_short} > 32));
then
	orig_ref="See description for Identifiers"
fi

# Option to generate PB Core Instantiation Doc

if [ "${1}" = "-pb" ]
then
	mediainfo --output=PBCore2 "$2" >"${2%.*}"_pbcoreinstantiationdocument.xml
	exit
fi

# Option to Edit Configuration File

if [ "${1}" = "-e" ]
then
	echo "#INSERT YOUR VALUES BETWEEN THE QUOTES AND SAVE FILE" > "${config_file}"
	echo "originator=\"$originator\"" >> "${config_file}"
	echo "history=\"$history\"" >> "${config_file}"
	echo "IARL=\"$IARL\"" >> "${config_file}"
	mate $config_file

else

# Run bwfmetaedit with selected settings on input file
date=$(mediainfo -f ${1} | grep "File last modification date (local)" | cut -c 44-53)
time=$(mediainfo -f ${1} | grep "File last modification date (local)" | cut -c 55-)

bwfmetaedit --reject-overwrite --Description="${1##*/}" --Originator="$originator" --OriginatorReference="$orig_ref" --History="$history" --IARL="$IARL" --MD5-Embed --OriginationDate="$date" \
--OriginationTime="$time" "${1}"

#Report Coding History for confirmation
echo -e "\033[1;95m ************ \033[0m"
echo -e "\033[1;93m Process complete. \033[0m"
echo -e "\033[1;93m The coding history contains the following values. \033[0m"
echo -e "\033[1;93m Please check for accuracy. \033[0m"
mediainfo -f "${1}" | grep "Encoding settings" | cut -c 44-
echo -e "\033[1;95m ************ \033[0m"
fi

exit
